steps:
- id: 'build'
  name: 'gcr.io/cloud-builders/docker'
  args:
  - build
  - --rm
  - --no-cache
  - --tag=gcr.io/$PROJECT_ID/rcran-build:$BUILD_ID
  - .

# Delete old images
- id: 'delete-old-images'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    set -e
    gcloud container images list-tags gcr.io/$PROJECT_ID/rcran-build --filter="NOT tags:latest timestamp.datetime < -P3M" --format='get(digest)' --limit 100 | xargs -I {} gcloud container images delete gcr.io/$PROJECT_ID/rcran-build@{} --quiet --force-delete-tags
    gcloud container images list-tags gcr.io/kaggle-images/rcran --filter="NOT tags:latest timestamp.datetime < -P3M" --format='get(digest)' --limit 100 | xargs -I {} gcloud container images delete gcr.io/kaggle-images/rcran@{} --quiet --force-delete-tags

# Pushing the intermediate image can be useful to debug test failures.
- id: 'intermediate-push'
  waitFor: ['build']
  name: 'gcr.io/cloud-builders/docker'
  args:
  - push
  - gcr.io/$PROJECT_ID/rcran-build:$BUILD_ID

# Verify 'convert' (ImageMagick) is available.
- id: 'test-convert'
  waitFor: ['intermediate-push'] # Otherwise the test failure should stop push.
  name: 'gcr.io/$PROJECT_ID/rcran-build:$BUILD_ID'
  args: ['convert', '--version']

- id: 'test'
  waitFor: ['intermediate-push'] # Otherwise the test failure should stop push.
  name: 'gcr.io/$PROJECT_ID/rcran-build:$BUILD_ID'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    set -e
    Rscript test_build.R
    # Verify expected test_build.R output is present.
    [ -s plot1.png ]
    echo "ok"

- id: 'retag'
  waitFor: ['test', 'test-convert']
  name: 'gcr.io/cloud-builders/docker'
  args:
  - tag
  - gcr.io/$PROJECT_ID/rcran-build:$BUILD_ID
  - gcr.io/kaggle-images/rcran:$_TAG

images: ['gcr.io/kaggle-images/rcran:$_TAG']

options:
  # Use of largest GCB instance size in shared pool.
  # Upon change, update Ncpus in package_installs.R.
  machineType: 'N1_HIGHCPU_32'
  diskSizeGb: 1000 # Max disk size. Gives more IOPS.

timeout: 86400s

substitutions:
  _TAG: testing # Change to latest for production.

tags: ['rcran', 'notification']