#!/bin/bash
set -e
set +x

label=${1:-testing}

docker tag kaggle/rcran-build:latest gcr.io/kaggle-images/rcran:${label}
gcloud docker -- push gcr.io/kaggle-images/rcran:${label}

if [[ "$label" == "latest" ]]; then
	docker tag kaggle/rcran-build:latest kaggle/rcran:${label}
	docker push kaggle/rcran:${label}
fi
