# Loosely based on http://www.kdnuggets.com/2015/06/top-20-r-packages.html

Library <- function(libname){
  print(libname)
  suppressPackageStartupMessages(library(libname, character.only=TRUE))
}

Library("bigrquery")
Library("bitops")
Library("colorspace")
Library("devtools")
Library("dichromat")
Library("digest")
Library("dplyr")
Library("dtwclust")
Library("fable")
Library("gapminder")
Library("ggplot2")
Library("gtable")
Library("hrbrthemes")
Library("IRkernel")
Library("jsonlite")
Library("knitr")
Library("labeling")
Library("leaflet")
Library("mime")
Library("munsell")
Library("plyr")
Library("prophet")
Library("proto")
Library("randomForest")
Library("RColorBrewer")
Library("Rcpp")
Library("RCurl")
Library("readr")
Library("reshape2")
Library("roxygen2")
Library("scales")
Library("seewave")
Library("sf")
Library("stringr")
Library("tidyr")
Library("udunits2")
Library("xgboost")
Library("zoo")

#Packages for Neurohacking in R coursera course
Library("oro.nifti")
Library("oro.dicom")
Library("fslr")

testPlot1 <- ggplot(data.frame(x=1:10,y=runif(10))) + aes(x=x,y=y) + geom_line()
ggsave(testPlot1, filename="plot1.png")
