#!/bin/bash
set -e

# Verify 'convert' (ImageMagick) is available.
docker run --rm -t --read-only --net=none kaggle/rcran-build convert --version

rm -rf /tmp/rcran-build
mkdir -p /tmp/rcran-build/tmp
mkdir -p /tmp/rcran-build/devshm
mkdir -p /tmp/rcran-build/working
docker run --rm -t --read-only --net=none -e HOME=/tmp -v $PWD:/input:ro -v /tmp/rcran-build/working:/working -w=/working -v /tmp/rcran-build/tmp:/tmp -v /tmp/rcran-build/devshm:/dev/shm kaggle/rcran-build /bin/bash -c 'Rscript /input/test_build.R'

# Verify expected test_build.R output is present.
[ -s /tmp/rcran-build/working/plot1.png ]

echo "ok"
